name: API call to Discord bot
on:
  schedule:
    - cron: "30 20 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: New discord message every day
        run: |
          curl --request POST \
          --url 'https://top3dumardi.vercel.app/api/discord-bot' \
          --header 'authorization: Bearer ${{ secrets.API_SECRET }}'
